coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 5%   # tolerância geral do projeto
    patch:
      default:
        target: 60%
        threshold: 10%  # tolerância para mudanças pequenas e difíceis de cobrir
