name: CI - Testes e Cobertura

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testar em Node.js 20
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🧪 Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: ✅ Rodar testes com cobertura
        run: npm run test:coverage
